Repository FRONTENDBOOTCAMP-12th/write-here, pull requests merged in 2025-03, with the labels that each got.

#53 [Feat] SubmitButton 컴포넌트 제작
  src/components/SubmitButton.tsx
  src/styles/global.css
Labels: 💼 Feature, 🔴 Priority : High

#59 [Feat] 체크박스 컴포넌트 제작
  public/icons/icon-check.svg
  src/components/Checkbox.tsx
Labels: 💼 Feature, 🟡 Priority : Medium

#56 [Feat] DiaryInput 컴포넌트
  src/components/DiaryInput.tsx
Labels: 💼 Feature, 🧹 Refactor

#62 [Feat] RecentVisitDisplay 컴포넌트 제작
  src/components/RecentVisitDisplay.tsx
Labels: 💼 Feature, 🟡 Priority : Medium

#61 Feat/toggle
  .gitignore
  src/components/Toggle.tsx
  src/pages/navigation-test/index.tsx
Labels: 🛠️ BugFix, 💼 Feature, 🧹 Refactor

#66 [Feat] ShowMore 컴포넌트 제작
  src/components/ShowMore.tsx
Labels: 💼 Feature, 🟡 Priority : Medium, 1-Level Component
